### ISSUE TITLE
Adding --isolated option

### ISSUE THREAD

**Issue by BertRaeymaekers** [pomponchik/instld#13]
I want pip to ignore what is in pip.conf during install

Solution I tries:  Adding an extra --constraint option but tthat doesn't work, it will only add to the constraints, not replace it as pip allows multiple constraints files.
So I wanted to use the --isolated option (https://pip.pypa.io/en/stable/cli/pip/#cmdoption-isolated). This is indeed not on https://pip.pypa.io/en/stable/cli/pip_install/ as it is a general pip option.

More context on my use-case:
I have a general constraint configuration in pip.conf for the application dependencies. I want to ignore because there is a dependency conflict between a dependency of my project and a dependency of pip-audit (a tool I want to run in my CI/CD pipeline against my pyproject.toml). So, I wanted to use instld to install/use pip-audit without having it in the main virtual environment, avoiding the conflict. But, it also takes into account the constraint in pip.conf (as it should). But having the isolated option should fix it for me.

**Comment by pomponchik** [comment]
Hello! I have added this since version 0.0.24.

**Comment by BertRaeymaekers** [comment]
Thanks 💯 !
🟢 Just tested it out and it works as expected!
