### ISSUE TITLE
Allow selecting python interpreter when using in REPL or Script launch mode

### ISSUE THREAD

**Issue by mortenlj** [pomponchik/instld#17]
When using instld to launch scripts, it would be very nice if you could select which python interpreter to use.

**Comment by pomponchik** [comment]
Hi!

At the moment, the interpreter is automatically used, the path to which you can see if you type `which python` in the console. You can change it, for example, by creating a virtual environment with the necessary interpreter and activating it before calling instld.

However, I suppose that's not exactly what you might have meant. How do you imagine your idea in terms of implementation?

**Comment by mortenlj** [comment]
My thought was that it could be a flag you use: `instld --python path/to/python script.py`. The idea was that when I have multiple versions of Python installed, I might have 3.11 on PATH, but want to use 3.9 for this particular script.

Creating a virtualenv for the script sort of invalidates the use of instld, because if I have a virtualenv for the script I might as well just install the dependencies in the virtualenv.

**Comment by pomponchik** [comment]
So, @mortenlj, what about this way?

```bash
path/to/python -m instld script.py
```

It is available now.

**Comment by mortenlj** [comment]
I guess that could work :+1:
